imgix/vue

.travis.yml
package.json

This PR adds travis config, which will do the following on every PR push:
- run lint (eslint + prettier)
- unit tests
- e2e tests

config: add travis config

---

.travis.yml

This PR configures Travis to deploy the next branch.

config(travis): deploy next [skip ci]

---

.travis.yml

This PR updates the Travis CI config to configure the deploy branch correctly.

config(travis): use proper branch config

---

package.json
yarn.lock

This is to try fix an error I was seeing on CI.

config: fix cypress version

---

.browserslistrc
.gitignore
.travis.yml
build/rollup.config.js
package.json
src/plugins/vue-imgix/wrapper.ts
yarn.lock

This PR adds Rollup and related config to start the process of publishing this library. Definitely not finished yet, but this is a big step in the right direction.

config: add config to prepare for publish

---

README.md
package.json
src/App.vue
src/components/simple/simple.vue
src/plugins/vue-imgix/component.ts
src/plugins/vue-imgix/vue-imgix.ts
tests/e2e/specs/advanced-api.spec.js
tests/e2e/specs/simple-api.spec.js
tests/unit/imgix-component.spec.ts
yarn.lock

feat: add basic imgix component and first steps towards simple API

---

package.json

config(semantic-release): use next channel for next branch

---

renovate.json

This PR adds a renovate config so that [Renovate](https://renovate.whitesourcesoftware.com/) will keep our dependencies up to date automatically. I copied this config from react-imgix.

config: add renovate config

---

build/rollup.config.js

chore: fix rollup build

---

README.md
src/components/simple/simple.vue
src/plugins/vue-imgix/types.ts
src/plugins/vue-imgix/vue-imgix.ts
tests/unit/initialization.spec.ts

feat: allow developers to disable ixlib param on initialization

---

README.md
src/plugins/vue-imgix/types.ts
src/plugins/vue-imgix/vue-imgix.ts
tests/unit/build-src-set.spec.ts
tests/unit/build-url-object.spec.ts

feat: allow developer to set min/max srcset widths for advanced API

---

README.md
src/plugins/vue-imgix/vue-imgix.ts
tests/unit/build-src-set.spec.ts
tests/unit/build-url-object.spec.ts

feat: support widthTolerance in advanced api

---

README.md
src/App.vue
src/components/advanced/advanced.vue
src/plugins/vue-imgix/ix-img.ts
src/plugins/vue-imgix/vue-imgix.ts
tests/e2e/specs/advanced-api.spec.js
tests/unit/imgix-component.spec.ts

feat: custom attribute mapping

---

README.md

docs: add note about vue 3

---

README.md

docs: add info about base64 encoding and lazy loading

---

README.md

docs: add setup docs for vue and nuxt

---

README.md
build/rollup.config.js
package.json
yarn.lock

config: fix rollup config

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

ssia. I've adapted these from react-imgix and updated slightly.

docs: add GH templates for PRs/issues

---

.vscode/settings.json

chore: disable format on save for vscode for this project

---

package.json
src/plugins/vue-imgix/vue-imgix.ts
yarn.lock

a) commit latest release, b) change package version

config(semantic-release): change semantic config

---

README.md
src/plugins/vue-imgix/ix-source.tsx

This PR also contains a small code fix of a typo left over from development

docs: update README in response to feedback

---

LICENSE
package.json

chore: relicense under bsd-2-clause

---

src/plugins/vue-imgix/ix-img.tsx

fix: small syntax error in disableVariableQuality code

---

.travis.yml

config: ensure project is built on every CI run to catch syntax errors

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md
.travis.yml
.vscode/settings.json
LICENSE
README.md
build/rollup.config.js
package.json
src/components/simple/simple.vue
src/plugins/vue-imgix/ix-img.tsx
src/plugins/vue-imgix/ix-source.tsx
src/plugins/vue-imgix/vue-imgix.ts
tests/helpers/url-assert.ts
tests/unit/imgix-component.spec.ts
yarn.lock

This PR will merge the beta changes into master, and semantic release *should* publish a new stable version.

Publish a stable version

---

README.md
tests/unit/imgix-component.spec.ts

chore: small fixed prop updates 

---

README.md
package.json
tests/unit/imgix-component.spec.ts

Deploy a stable build

---

README.md

This PR makes a small change to the code examples in the docs to make sure the imports are correct.

docs: remove references to @/plugins

---

README.md

This PR updates the suggested config for Nuxt.js to ensure that vue-imgix will run on the server.
Closes #162.
- [N/A] Add new passing unit tests to cover the code introduced by your PR
- [N/A] Update or add any necessary API documentation
Related issue: #162
Code:
Steps:
1.  Setup a nuxt project according to the README
2.  Write any vue-imgix code
3.	Ensure the image is rendered on page load

docs: update nuxt.js suggested config to fix server rendering

---

README.md

This PR fixes a change that was made in #186

docs: fix broken ref

---

.eslintrc.js
.prettierrc
package.json
src/plugins/vue-imgix/index.ts
src/plugins/vue-imgix/types.ts
yarn.lock

This PR updates the lint rules and some lint errors that were breaking the main build.

chore: fix lint errors and config

---

README.md

The readme is missing a v-bind before the imgixParams.  Without this, it does not correctly add the imgixParams to each srcset.

added v-bind to imgixParams

---

README.md

This PR updates [the readme](/README.md) to make it easier to read code block comments and clarify that setting `width` and `height` on a `fixed` image element will set the image's dimensions according to a devices DPR.

docs: update readme comments for clarity

---

src/plugins/vue-imgix/ix-img.tsx
src/plugins/vue-imgix/ix-picture.tsx
src/plugins/vue-imgix/ix-source.tsx
src/plugins/vue-imgix/vue-imgix.ts

Change types imports from `@/...` to `./..` relative imports.

chore: change @ imports to relative imports

---

README.md

Update this message since it's a bit awkward now
@sherwinski you can merge if you're happy with the language

docs: update Vue 3 message

---

package.json
yarn.lock

Add Dev deps. needed to be able to build and serve the vue app.

chore: add deps needed to serve without errors

---

README.md

docs: add nuxt-3 readme documentation

---

README.md

This PR adds info about how to install this library with Nuxt v3

docs: add Nuxt 3 info

---

package.json
yarn.lock

Update dependency to `@imgix/js-core@next`. This allows us to make use of the latest dependency update to `js-core`.

fix(deps): update js-core to v3.6.1-rc.1

---

.github/workflows/add-pr-to-project.yml

The add PR to project action name was wrong. This PR fixes it.

chore: fix action title

---

package.json

This PR updates `@imgix/js-core` to the latest version. Previously, this library was using a pre-release version of core.

chore(deps): update js-core to v3.7.0

---

README.md

chore: update ci badge

---

package.json
yarn.lock

Reverts imgix/vue#461
Renovate went AWOL and merged this in without CI passing.

Revert "chore(dev-deps): update dependency read-pkg to v7"

---

README.md

This PR updates the codesandbox example in README to one using vue 3.

[PE-3859] docs: updates readme with vue3 codesandbox

---

.circleci/config.yml

Build was breaking in CircleCI
Testing to see if bumping the browser-tools would fix it.

chore: updates browser-tools orb
