README.md, src/App.vue, src/components/advanced/buildUrl.vue, src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts, tests/e2e/specs/advanced-api.spec.js, tests/unit/build-url-spec.ts
This PR implements the second part of the advanced api, `buildUrl`, which is simply a re-export of buildUrl from `imgix-core-js`.
=> feat: implement buildUrl helper

.travis.yml, package.json, src/plugins/vue-imgix/vue-imgix.ts
This PR sets up semantic release to automatically publish the `next` branch to NPM under the `next` distribution channel. The `next` distribution channel is **not** installed by default when a user installs vue-imgix with `npm install vue-imgix`.
For now, we will have to manually deploy any releases on the `master` branch. I will work how to do this with semantic-release. In the future, if we are comfortable with semantic-release, we can enable automatic deployments on master too, and still have this flow.
This way, we still get to test how automatic deployment works, while still having control of what end users install.
We could potentially use `next` as an internal beta channel, if we wanted.
I decided that this was the best way to get started with automatic deployment, but also have it …
=> config: setup semantic-release

README.md, src/App.vue, src/components/advanced/buildSrcSet.vue, src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts, tests/e2e/specs/advanced-api.spec.js, tests/unit/build-src-set.spec.ts, tests/unit/build-url.spec.ts
This PR re-exposes buildSrcSet from imgix-core-js to allow developers to build src sets however they like.
=> feat: implement buildSrcSet

README.md, src/main.ts, src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts, tests/unit/initialization.spec.ts
This is done with the code
```js
Vue.use(VueImgix, {
defaultIxParams: {
auto: "format"
}
});
```
=> feat: allow developers to set default imgix parameters globally

.travis.yml, package.json
This PR updates the semantic config to use the default config so we can use continuous deployment for stable builds.
=> config: change semantic config

README.md, src/components/simple/simple.vue, src/plugins/vue-imgix/ix-img.tsx, tests/helpers/url-assert.ts, tests/unit/imgix-component.spec.ts
This PR follows on from internal discussions about how to best handle the new aspect-ratio placeholder behaviour of modern browsers. We agreed that the best way to handle this was with a `fixed` prop. The idea is that if this prop isn't present (i.e. by default), the image will render in responsive mode. This allows the user to pass a width and height (as they would for a normal `<img>`), and have it specify a responsive-aware placeholder for the image before it is loaded. Previously this was incompatible with our API because the width and height would instead load a fixed-size image. Now, developers will have to pass a `fixed` prop (or, although undocumented, they could also just pass width and height into imgixParams explicitly) for this component to render in a "fixed" mode.
=> feat: add fixed prop

package.json
The package.json version wasn't being updated, so I fixed it.
=> chore: update semantic-release plugin order

README.md
This PR adds a pair of `` comments around the table in the "Contributors" section of the README.md doc. We've decided that trying to render All-Contributor's table layout nicely is too much effort (since we have no control over the markup) when rendering our SDK READMEs directly on docs.imgix.com. The tags added in this PR will instruct the build pipeline over on the Docs side to ignore the annotated section.
=> Add tags to ignore all-contributors table on docs.imgix.com

README.md
The purpose of this PR is to correct a small typo in the opening paragraph.
The change makes `react-imgix` say `vue-imgix`. I only found two instances
of "react" here.
=> docs(readme): correct small typo

src/plugins/vue-imgix/ix-picture.tsx, src/plugins/vue-imgix/ix-source.tsx
This PR fixes an issue where JSX was being incorrectly used in this project. In development and in the tests this works since it is using the Vue CLI, which transpiles JSX correctly. Unfortunately, the build step processed the JSX differently, which wasn't picked up in testing.
This PR removes JSX from IxPicture and IxSource so that they work correctly.
This fixes #163 
- [N/A] Add new passing unit tests to cover the code introduced by your PR
- [N/A] Update the readme
- [N/A] Update or add any necessary API documentation
Related issue: #163
Code:
```js
<ix-picture>
<ix-source
src="examples/pione.jpg"
media="(min-width: 768px)"
:imgixParams="{ ar: '2:1', fit: 'crop' }"
/>
<ix-source
src="examples/pione.jpg"
media="(min-width: 320px)"
:imgixParams="{ ar: '1.5:1' }"
/>
<ix-img …
```
=> fix: picture mode throwing error

.prettierrc, package.json
Semantic-release wasn't happy that we removed the master branch so I configured it to use the main branch instead.
=> config: configure semantic release to work with new default branch

package.json, yarn.lock
ssia.
Renovate waits for all status checks before merging. Unfortunately, in this case, the travis status check didn't register (probably related to the issues we've had with Travis recently), so Renovate merged the PR even though the travis build would eventually fail. For now I've added the travis status check as a required check, and upgraded imgix-git-robot to admin so that semantic release will still work (see #5 [here](https://paper.dropbox.com/doc/Continuous-Delivery-for-SDK-libraries--A6TRzsS8aEVdXUkzURFIpimsAg-cwvR6vErtYImIbQaJHBkX#:uid=478409582922117316091303&h2=Installing-semantic-release)) for more info.
=> chore: revert dep update that broke build

package.json, yarn.lock
This PR fixes/resolves the Cypress version to 3.8.3 (the version that the vue cli asks for) and avoids conflicting cypress version numbers from different packages
=> chore: fix cypress version

.travis.yml, package.json, renovate.json
This PR updates the auto-release/dependency workflow to adopt imgix's shared Renovate config and changes needed due this adoption. Specifically:
- Renovate's config is based on the shared imgix configuration
- Travis no longer builds PRs, and instead builds all branches
- Semantic release will release dependency (excl. dev dependency) updates, as well as doc PRs (previously it didn't release these)
=> config: update auto-release workflow

src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts
This PR fixes a typescript error where `IVueImgixClient` was not being exported by `./types`.
Tested locally with `yarn test` and produced no errors.
Run `yarn serve` on `main` and see the error. Run `yarn serve` on this branch and see no error.
=> chore: explicitly export & import type IVueImgixClient

README.md, build/rollup.config.js, package.json, src/App.vue, src/components/simple/static-api.vue, src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts, vue.config.js, yarn.lock
- This PR adds static `_buildURL` and `_buildSrcSet` methods to the `VueImgixClient`.
- It assumes these static methods have been defined on the `@imgix/js-core` dependency [pending].
This PR needs to be updated to include better logic on detecting full path, or 1-step, URLs. As it stands, we only check for the `://` delimiter. This won't be sufficient for some edge cases.
=> feat: add full url static methods

.travis.yml
This fixes a build issue between Node v17 and Webpack.
More info: https://github.com/webpack/webpack/issues/14532
=> chore: use Node v16

.travis.yml, package.json, src/components/simple/ix-picture.vue, src/plugins/vue-imgix/ix-picture.tsx, tests/unit/imgix-component.spec.ts, tests/unit/picture-mode.spec.tsx
This PR updates the `slot` syntax to match the vue 3 [composition API](https://v3.vuejs.org/guide/composition-api-setup.html#context) usage in the `setup()` function.
This PR also updates the test specs to remove as much use of `@testing-library/vue` usage as possible. That library isn't quite ready for Vue 3 yet and was blocking our migration efforts. It's been replaced by more direct usage of `@vue/test-utils`.
- `ix-picture` component was still using Vue 2 `this.$slots.defaults` syntax. This lead to rendering issues and even App crashes
- The test suite was still relying on `@test-utils/vue` rc.
- CI tests were failing due to `unsupported envelope routine` errors
- CI tests were failing due to Electron issues with headless test running
- `ix-picture` component now uses the composition …
=> chore: update slot syntax to vue 3

.travis.yml, README.md, build/rollup.config.js, package.json, src/App.vue, src/components/advanced/_buildSrcSet.vue, src/components/simple/static-api.vue, src/plugins/vue-imgix/types.ts, src/plugins/vue-imgix/vue-imgix.ts, tests/e2e/specs/static-api.spec.js, tests/unit/build-src-set.spec.ts, tests/unit/build-url.spec.ts, yarn.lock
This PR adds `_buildURL` and `_buildSrcSet` methods to the vue imgix client and enables users to use absolute URLs as the `img` src attribute. This means that users can override the imgix client domain on a per-image basis.
Fixes: #435
=> feat: create build URL and srcset methods

tests/unit/build-src-set.spec.ts
This PR adds back the srcset tests that were removed in https://github.com/imgix/vue-imgix/commit/78ce8cf886b852065523fe36b7d8acfa07fc9a0f
=> tests: add back src set mocks

README.md
This PR adds a notice to the Vue 2 maintenance branch to mention Vue 3 support.
=> docs: add information about Vue 2 deprecation

README.md
**🚨 Don't merge this PR.** This PR only exists for review purposes, and after completing the steps below this branch should be deleted.
When this repository is renamed, we should publish this branch to the `vue-imgix` npm repository to add a notice on NPM that the package has been renamed. When publishing this version, we should also deprecate this package with the following commands:
```sh
npm deprecate vue-imgix "vue-imgix has been renamed to @imgix/vue. Install @imgix/vue instead of this package."
```
=> chore: add rename message [don't merge]

package.json
Adds additional scripts to ensure properly updated `dist` prior to release.
Library is not guaranteed to execute a `build` step to properly update `dist` directory prior to deployment; as a result, some libraries include the prior release in their `dist` folder.
We include both a `prepare` and a `prepublishOnly` step to ensure that the library executes a build prior to deploying a release.
=> ci(deploy): add prepare step

yarn.lock
This PR updates the `yarn.lock` file so that the `@achrinza/node-ipc@^9.2.5` dep resolves to v9.2.6, introducing node v19 compatibility. This unblocks some CI work upstream.
=> chore(deps): update node-ipc to 9.2.6

README.md
This PR changes the following:
- removes the warning icon for the vue 2 note
- removes the FOSSA bot badge
- updates the license portion of the readme
- ~updates the contributors in the `package.json`~
=> docs(readme): remove fossa badge and update contributors

README.md
This PR adds `@2.9.0` to the npm and yarn install examples to ensure users install the Vue 2 compatible version of this package when reading the README.
It also removes the FOSSA badge.
=> chore(readme): add explicit version number to readme and remove fossa badge

.vscode/settings.json, README.md
Correct readme instructions to use "&" instead of "&amp;" to chain parameters.
Same for output HTML code snippets.
=> fix(readme):remove html encoding from parameter strings
